# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# Importar las utilidades de Flutter para CocoaPods
require_relative 'Flutter/generated_podhelper.rb'

# CocoaPods analytics sends usage stats.
# cocoapods_analytics

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Asegura que todos los pods y dependencias se compilen con iOS 13.0 como mínimo
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
