name: Compilar iOS IPA para SIRCAM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar entorno de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Generar archivos de Isar Database
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Descargar artefactos de iOS (Precache)
        run: flutter precache --ios

      - name: Generar archivos de configuracion de Flutter iOS
        run: flutter build ios --config-only

      - name: Compilar instalador iOS (IPA)
        run: flutter build ipa --release --no-codesign

      - name: Guardar paquete ejecutable generado
        uses: actions/upload-artifact@v4
        with:
          name: sircam-ios-ipa
          path: build/ios/archive/Runner.xcarchive
